Caught Exception2
finally
Done!
